version: '3.7'
services:
#  propay:  propay
#    image: propay
#    container_name: propay
#    restart: always
#    ports:
#      - "8080:80"
#    depends_on:
#      - ausleiherino


#  ausleiherino:
#    container_name: ausleiherino
#    build: .
#    volumes:
#      - .:/app
#    working_dir: /app
#    user: appuser
#    environment:
#      - POSTGRES_PASSWORD=secret
#      - POSTGRES_DB=database
#      - POSTGRES_USER=postgres
#    command: dockerize -wait tcp://database:5432 -timeout 600s ./gradlew bootRun

  database:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    external: true

