version: '3.5'
services:
  # (production)
  #  propay:
  #    container_name: propay
  #    image: propra/propay:latest
  #    restart: always
  #    ports:
  #      - 8888:8888
  #    volumes:
  #      - ./PPdata:/code/data

  # (final)
  propay:
    container_name: propay
    image: propra/propay:latest
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./PPdata:/code/data

  # (dev)
  ausleiherino24:
    container_name: ausleiherino24
    build:
      context: ./
      dockerfile: ausleiherinoDevDockerfile
    volumes:
      - .:/app
    working_dir: /app
    #     user: appuser
    ports:
      - 8080:8080
    env_file:
      - ./.env
    command: java -jar app.jar
    depends_on:
      - db
      - propay


  #   (production)
  #    ausleiherino24:
  #      container_name: ausleiherino24
  #      build:
  #        context: ./
  #        dockerfile: ausleiherinoProdDockerfile
  #      volumes:
  #        - .:/app
  #      working_dir: /app
  #      user: appuser
  #      ports:
  #        - 8080:8080
  #      env_file:
  #        - ./.env
  #      command: dockerize -wait tcp://db:5432 -timeout 600s java -jar app.jar

  #  (development)
  #  db:
  #    container_name: pgsql-01
  #    build:
  #      context: ./
  #      dockerfile: PGSQLDockerfile
  #    restart: always
  #    user: "${PUID}:${PGID}"
  #    ports:
  #      - 5432:5432
  #    env_file:
  #      - ./.env
  #    volumes:
  #      - ./pgsql-01/data:/var/lib/postgresql/data
  #      - ./pgsql-01/conf:/config

  # (production)
  db:
    container_name: pgsql-01
    build:
      context: ./
      dockerfile: PGSQLDockerfile
    restart: always
    user: "${PUID}:${PGID}"
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./pgsql-01/data:/var/lib/postgresql/data
      - ./pgsql-01/conf:/config

#  jenkins:
#    container_name: jenkins
#    image: jenkins/jenkins:latest
#
#    restart: unless-stopped
#    ports:
#      - 9000:8080
#      - 50000:50000
#    volumes:
#      - ~/jenkins_home:/var/jenkins_home
