version: '3.5'
services:
  propay:
    image: propra/propay:latest
    container_name: propay
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./PPdata:/code/data

  #  ausleiherino24:
  #    container_name: ausleiherino24
  #    build: .
  #    volumes:
  #      - .:/app
  #    working_dir: /app
  #    user: appuser
  #    ports:
  #      - 8081:8081
  #    env_file:
  #      - ./.env
  #    command: dockerize -wait tcp://localhost:5432 -timeout 600s  -wait tcp://localhost:8888 -timeout 600s./gradlew bootRun

  # (production)
  db:
    build:
      context: ./
      dockerfile: PGSQLDockerfile
    restart: always
    container_name: pgsql-01
    user: "${PUID}:${PGID}"
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./pgsql-01/data:/var/lib/postgresql/data
      - ./pgsql-01/conf:/config

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - ~/jenkins_home:/var/jenkins_home
