version: '3.5'

services:
  propay:
    container_name: propay
    image: propra/propay:latest
    restart: always
    volumes:
      - ppdata:/code/data

  ausleiherino24:
    container_name: ausleiherino24
    build:
      context: ./
      dockerfile: ausleiherinoDockerfile
    working_dir: /app
    links:
      - "propay:propay"
      - "db:db"
    ports:
      - 8080:8080
    env_file:
      - ./.env
    volumes:
      - uploads:/app/uploads
    entrypoint: dockerize -wait tcp://db:5432 -timeout 60s -wait tcp://propay:8888 -timeout 60s
    command: java -cp /app/resources:/app/classes:/app/libs/* de.propra2.ausleiherino24.Ausleiherino24Application

  db:
    container_name: pgsql-01
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  uploads:
  ppdata:
