version: '3.5'
services:
  propay:
    image: propra/propay:latest
    container_name: propay
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./propaydata:/code/data
  #   depends_on:
  #     - ausleiherino24

  #  ausleiherino24:
  #    container_name: ausleiherino
  #    build: .
  #    volumes:
  #      - .:/app
  #    working_dir: /app
  #    user: appuser
  #    environment:
  #      - POSTGRES_PASSWORD=secret
  #      - POSTGRES_DB=database
  #      - POSTGRES_USER=postgres
  #    command: dockerize -wait tcp://database:5432 -timeout 600s ./gradlew boot

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./database:/var/lib/postgresql/data

#  sonardb:
#    container_name: sonardb
#    image: postgres
#    hostname: pgsql-01
#    ports:
#      - 4321:4321
#    environment:
#      - POSTGRES_PASSWORD=sonar
#      - POSTGRES_DB=sonar
#      - POSTGRES_USER=sonar
#    volumes:
#      - ./sonardb:/var/lib/postgresql/data
#
#  sonarqube:
#    container_name: sonarqube
#    image: sonarqube
#    hostname: sonar-01
#    links:
#      - sonardb
#    ports:
#      - 9000:9000
#    environment:
#      - SONAR_JDBC_URL=jdbc:postgresql://pgsql-01:4321/sonar
#      - SONAR_JDBC_USERNAME=sonar
#      - SONAR_JDBC_PASSWORD=sonar
#
#  jenkins:
#    image: 'jenkins/jenkins:lts'
#    container_name: jenkins
#    restart: unless-stopped
#    ports:
#      - 1234:1234
#    volumes:
#      - ./jenkins_home:/var/jenkins_home
