version: '3.5'
services:
  propay:
    image: propra/propay:latest
    container_name: propay
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./PPdata:/code/data

  #   depends_on:
  #     - ausleiherino24

  #  ausleiherino24:
  #    container_name: ausleiherino
  #    build: .
  #    volumes:
  #      - .:/app
  #    working_dir: /app
  #    user: appuser
  #    environment:
  #    - POSTGRES_USER=${POSTGRES_USER}
  #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #    - POSTGRES_DB=${POSTGRES_DB}
  #    command: dockerize -wait tcp://localhost:5432 -timeout 600s ./gradlew boot

  db:
    build:
      ./pgsql-01
    restart: always
    container_name: pgsql-01
#    user: "${PUID}:${PGID}"
    ports:
      - 5432:5432
    env_file:
      - ./.env
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_USER}
#      - POSTGRES_USER=test
#      - POSTGRES_PASSWORD=test
#      - POSTGRES_DB=${pgsql-01_DB}
    volumes:
      - ./pgsql-01/persistence/data:/var/lib/postgresql/data
      - ./pgsql-01/persistence/conf:/config

#  jenkins:
#    image: 'jenkins/jenkins:lts'
#    container_name: jenkins
#    restart: unless-stopped
#    ports:
#      - 1234:1234
#      - 50000:50000
#    volumes:
#      - ./jenkins_home:/var/jenkins_home
