.PreCleanup
[source,bash]
----
Execute customtasks/dockerReset task
From within projectroot do:
sudo rm -rf ~/.gradle
sudo rm -rf ./.gradle
sudo rm -rf ./build
sudo rm -rf ./out
sudo rm -rf ./jenkins_home
sudo rm -rf ./propay
----

.Importing the code-style settings in the intelliJ formatter:
`File -> Settings -> Editor -> Code Style -> Java -> Import Scheme -> "three little dots" -> IntelliJ Idea code style XML -> Then use ./config/checkstyle/intellij-java-google-style.xml`

.Force code formatting on every commit:
`File -> Settings -> Version Control -> Commit Dialog -> Then check the following:`

  * Reformat code
  * Rearrange code
  * Optimize imports
  * Cleanup

(Rest can/should be unchecked)

The following plugins have proven to be quite useful (and should be used (!)). Once enabled they will fetch all commits from the branches,
so you always realize once the branch you are currently working on has changed and can repull/merge quickly.
(Dont remember which one ^^)

(Settings -> Plugins -> Marketplace) +
Git Extender +
GitToolBox +
Git Integration +
GitHub +
GitLink +

Asciidoc +
Lombok +
Rainbow Brackets +
PMDplugin +
FindBugs-IDEA (=Spotbugs) +
SonarLint +
Hibernate Support +
Thymeleaf +
all Spring related default addons


Custom VM Options mit 2gb schreibe ich hier mal rein, einer von euch hatte gesagt es intellij laggt.

```
-server
-Xms2g
-Xmx2g
-Xss16m
-XX:+UseConcMarkSweepGC
-XX:+CMSParallelRemarkEnabled
-XX:ConcGCThreads=4
-XX:ReservedCodeCacheSize=256m
-XX:+AlwaysPreTouch
-XX:+TieredCompilation
-XX:+UseCompressedOops
-XX:SoftRefLRUPolicyMSPerMB=50
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-Djsse.enableSNIExtension=true
-Dide.no.platform.update=true
```

Die laufen bei mir soweit sehr stabil momentan. Findet man unter Help -> Edit Custom VM Options.
