= ausleiherino24

IMPORTANT: When first importing the project `Create separate module per source set` must be **unchecked.** +
           If cleanup is desired, make sure to follow all steps of init.adoc again.

== Login Details
  * as user :
    - username : user
	- password : password
  * as admin :
	- username : admin
	- password : password

== gradle configuration/tasks
**bootRun** now automatically starts propay on 8888 and postgres on 5432 (As soon as we switch to production phase). The folder structure is generated automatically and the app will be started first once postgres is ready. The app will be running on 8080 as usual.

=== customtasks folder in gradle-tasks
**manualInit** can trigger the folder structure creation manually if needed.

**cleanUp** tries to delete all folders and caches created, though it may be possible that it fails with a permission error, then one can run the clean.sh with elevation like so: `sudo ./scripts/clean.sh`.

**dockerReboot**, **dockerClean**, **dockerReset** do cleanup tasks in different intensitys.
(Delete Containers only, delete containers and images, delete everything including volumes)

== docker
Permissions of the database persistence folder (pgsql-01) are synchronized with the invoking user, so that it should be visible and accessible from within the IDE.

Services that are desired to be started can be enabled/configured in ./config/gradle/docker-compose.gradle

Logs of all running services can be found at ./build/logs/

== jenkins
Does the same as travis, just more and better. It can be reached on localhost:9000 (if enabled in ./config/gradle/docker-compose.gradle). Persistent local storage is located at ~/jenkins_home.

== javadocs
The task _javadocs_ generates its output to ./build/docs/javadoc/de. 

== code-style
All files containing sourcecode are formatted according to the Google Java Style Guide (https://google.github.io/styleguide/javaguide.html). Code formatting is enforced on every commit.

 **First time configuration of the IDE is necessary (see init.adoc)**

HINT: Use CTRL+ALT+L (or Code -> reformat code) to manually trigger a code format of the currently opened file.

To get visual feedback regarding styleguide violations on-the-fly check "Treat Checkstyle errors as warnings." and configure the checkstyle intellij plugin like so: +
`File -> Settings -> Other Settings -> Checkstyle -> + -> Use local checkstyle-file and set a name` +

== Code Analysis
=== sonarcloud
The app is now available online on sonarcloud  at https://sonarcloud.io/organizations/ausleiherino24/.

Running the gradle-task _sonarqube_ will trigger a new analysis run, but the analysis is also automatically triggered on every new commit by travisCI.

The plugin _SonarLint_ marks sonarqubes findings locally in the IDE.

=== PMD
To perform a local PMD run with the intellij PMD plugin do the following: 

`Settings -> Other Settings -> PMD -> + and then select ./config/pmd/ruleset.xml.` +
To run the analysis: Tools -> Run PMD -> custom rules -> ruleset. +

=== General
Spotbugs, Pitest ("tests the tests"), jacoco (coverage) and the build time is being run/calculated automatically along with the task _check_. Its output is visible via stdout on the console.
